# Generated by Django 3.0.8 on 2021-01-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanctuary', '0002_auto_20201230_0123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionView',
        ),
    ]
