# Generated by Django 3.0.8 on 2021-01-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sanctuary', '0003_delete_sessionview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specie',
            new_name='Statistic',
        ),
    ]
